### ISSUE TITLE
Home Assistant Addon

### ISSUE THREAD

**Issue by boennemann** [reinhard-brandstaedter/solarflow-control#204]
Hey all,

I'm planning to run the docker container as a Home Assistant Add-on directly on my Home Assistant Yellow – as I understood an add-on is anyway just a super slim layer of metadata on top of docker containers.

Before I dive into that I wanted to open the discussion already.

1) Has anyone done this before and can share something?
2) Are there any reasons I'm missing why this is either a bad idea or not possible
3) Once I've got it working I'd love to contribute the setup back, ideally getting this into Home Assistant as an Add-On without the need to fork.

Let me know what you think!

**Comment by busaku** [comment]
I would love an direct HA-Addon :)

**Comment by boennemann** [comment]
In the end it's really just a matter of 3 steps

1) copying the contents of the `src/` folder to `/addons/solarflow-control`
2) adding config.yaml, here is mine: 
```yml
name: "Solarflow Control"
description: "Solarflow Control"
version: "0.0.1"
slug: "solarflow_control"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
 ```
3) I added this one line to the Dockerfile: `COPY ./config.ini /solarflow/config.ini`
